In [1]:
sum([1,2,3])

6

In [2]:
%history

sum([1,2,3])
%history


In [3]:
! touch file.py

In [ ]:
# %load file.py
print("Line one")
print("Line two")

In [5]:
%run file.py

Line one
Line two


In [6]:
%time sum([1,2,3,4,5])

Wall time: 0 ns


15

In [7]:
sum([1,2,3])

6

In [4]:
s1=list(range(1,20000))
print(s1[:10])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
for i in s1[:10]:
    i+=5
    print(i ,end=" ")
print("\n")
print(s1[:10])

6 7 8 9 10 11 12 13 14 15 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


# Python vs Numpy

In [1]:
import numpy as np
l1=[1,2,3,4,5,5]
print(sum(l1))
print(np.sum(l1))

20
20


In [3]:
%time sum(l1)
%time np.sum(l1)

Wall time: 0 ns
Wall time: 0 ns


20

In [4]:
%time l1=list(range(1,3000))
l1[:20]

Wall time: 0 ns


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [12]:
%time [x+5 for x in l1][:10]

Wall time: 377 ms


[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [35]:
for i in l1[0:10]:
    i=i+5
    print(i,end=" ")

6 7 8 9 10 11 12 13 14 15 

In [5]:
[i+5 for i in l1[:10]]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [8]:
l3 = [[1,2,3],
     [4,5,6],
     [7,8,9]]
for ri,rv in list(enumerate(l3)):
    for ci,cv in list(enumerate(rv)):
        l3[ri][ci]+=5
print(l3)

[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [17]:
l4=[[21,12,23],[5,36,27],[19,18,17]]
for i,rv in list(enumerate(l4)):
    for x,cv  in list(enumerate(rv)):
        l4[i][x]+=3
l4

[[24, 15, 26], [8, 39, 30], [22, 21, 20]]

In [37]:
list(enumerate(['A','B','C']))

[(0, 'A'), (1, 'B'), (2, 'C')]

In [22]:
list(enumerate(('a','b','c','d')))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [56]:
for i,v in list(enumerate(l1)):
    l1[i]=l1[i]+5
l1[:10]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [18]:
x=list(range(10,21))
x

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [43]:
l1=['repeat','sleep','eat']
for i in enumerate(l1):
    print(i)
print("\n")
for i in enumerate(l1,20):
    print(i)

(0, 'repeat')
(1, 'sleep')
(2, 'eat')


(20, 'repeat')
(21, 'sleep')
(22, 'eat')


In [1]:
# print(l1)
# for i,v in list(enumerate(l1)):
#     l1[i] = l1[i]+5
# print(l1[:10])
# # what is this on every execution shows differnrt output


NameError: name 'l1' is not defined

In [30]:
l11=[9,8,7,6,5,4,3,2,1,12,13,14,15,16,17,18,19,20]
for i,v in list(enumerate(l11)):
    l11[i]+=2
l11

[11, 10, 9, 8, 7, 6, 5, 4, 3, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [42]:
l11=[9,8,7,6,5,4,3,2,1,12,13,14,15,16,17,18,19,20]
 print(l11)
for i in l11:
    i+=5
    print(i,end=" ")

[9, 8, 7, 6, 5, 4, 3, 2, 1, 12, 13, 14, 15, 16, 17, 18, 19, 20]
14 13 12 11 10 9 8 7 6 17 18 19 20 21 22 23 24 25 

In [27]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
print("Before Adding 5")
print(a)
for ri, rd in list(enumerate(a)):
    for ci, cd in list(enumerate(rd)):
        a[ri][ci] += 5
        

print("After Adding 5")
print(a)

Before Adding 5
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
After Adding 5
[[6, 7, 8], [9, 10, 11], [12, 13, 14]]


In [45]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
a=np.array(a)
# a.dtype
# a.ndim
a+5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# NUMPY

In [2]:
import numpy as np

In [69]:
%time l2=np.arange(1,30000)

Wall time: 0 ns


In [72]:
l1=np.array([1])
print(l1.ndim)
print(l1.shape)
print(l1.dtype)

1
(1,)
int32


In [75]:
l1=np.random.randn(2,2)
l1

array([[0.11391436, 0.59014646],
       [0.27614925, 1.35123818]])

In [76]:
print(l1.ndim)
print(l1.dtype)
print(l1.shape)

2
float64
(2, 2)


In [79]:
l1=np.random.randn(3,2,2)
l1

array([[[-0.48654625,  0.51482575],
        [ 0.28613108,  0.76076833]],

       [[-2.08660972,  1.23326512],
        [-1.09133082, -0.61784527]],

       [[ 0.2738563 ,  0.37645628],
        [ 0.54174293, -1.35008757]]])

In [80]:
print(l1.ndim)
print(l1.dtype)
print(l1.shape)

3
float64
(3, 2, 2)


In [83]:
l1=np.arange(27).reshape(3,3,3)
print(l1)
print(l1.ndim)
print(l1.shape)
print(l1.dtype)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
3
(3, 3, 3)
int32


# A Multidimensional Array Object

In [84]:
l1 = np.arange(1,11)
print(l1)
print("Dimension:", l1.ndim)
print("Shape:", l1.shape)
print("Type:", l1.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
Dimension: 1
Shape: (10,)
Type: int32


In [35]:
a=np.arange(1,28).reshape(3,3,3)
print(a)
a[1,2,1]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


17

In [3]:
b=np.arange(1,28).reshape(3,3,3)
print(b)
print(b[b%3==0])


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[ 3  6  9 12 15 18 21 24 27]


In [4]:
b+3

array([[[ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21]],

       [[22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]]])

In [6]:
b*2

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[38, 40, 42],
        [44, 46, 48],
        [50, 52, 54]]])

In [7]:
b**2

array([[[  1,   4,   9],
        [ 16,  25,  36],
        [ 49,  64,  81]],

       [[100, 121, 144],
        [169, 196, 225],
        [256, 289, 324]],

       [[361, 400, 441],
        [484, 529, 576],
        [625, 676, 729]]], dtype=int32)

# Creating ndarrays

In [8]:
a=[1,2,3,4]
n=np.array(a)
# Deep copy

In [9]:
n is a

False

In [10]:
a is n

False

In [11]:
# 1 array->Same Datatype->Shallow Copy
# 2 array->Change dtype -> Deep Copy
# 3 if not array->Deep copy
l = [1,2,3,4,5,6,7]
print(type(l))

a = np.asarray(l) #3
b = np.asarray(a) #1
c = np.asarray(a, dtype=np.float64)#2

print(a is b) # 2
print(l is a) # 1
print(c is a) # 3
type(a)

<class 'list'>
True
False
False


numpy.ndarray

In [2]:
c=np.array([1,2,3])
c.itemsize

4

In [3]:
a=np.array([1,2,3,4])
b=np.asarray([1,2,3])

In [6]:
print(a.dtype)
print(b.dtype)
a.ndim

int32
int32


1

In [2]:
import numpy as np
x=np.arange(1,14)


In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
x.itemsize

4

In [6]:
def A(x):return x+5
A(7)

12

In [7]:
def B(c):return c+19
B(44)

63

In [8]:
def A(x):return x+5
def B(x):return x+6    
def C(x):return x+7

In [9]:
C(B(A(1)))

19

In [10]:
a=np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [11]:
b=np.reshape(np.arange(1,28),(3,3,3))
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [12]:
a = np.arange(1,28)
print(a)
print(a.ndim)
a.shape = (3,9)
print(a.ndim)
a

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
1
2


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [13]:
a.shape=(9,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [13]:
np.zeros((3,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
a.shape

(9, 3)

In [10]:
c=np.arange(1,28)
print(c)
print(c.shape)
c.shape=(3,9)
print(c.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]
(27,)
(3, 9)


In [18]:
np.zeros((a.shape[0],a.shape[1]))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.zeros(a.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
Z = np.zeros((10,10))
# print("%d bytes" % (Z.size * Z.itemsize))
print((Z.size * Z.itemsize))

800


In [56]:
z= np.zeros((8,8),dtype=int)
z
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[1 1 0 1]
 [1 2 1 0]
 [0 1 3 1]
 [1 0 1 4]]


In [26]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [57]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [27]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [28]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.05277989 0.13201892 0.99757087]
  [0.94491054 0.47579928 0.57220517]
  [0.64497574 0.9268349  0.81609432]]

 [[0.13031024 0.24184487 0.43665977]
  [0.58526584 0.58228179 0.18296983]
  [0.23255058 0.81428815 0.14267814]]

 [[0.43342929 0.15244155 0.13427832]
  [0.46089968 0.92018493 0.21825928]
  [0.73717124 0.87916126 0.90918945]]]


In [35]:
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
print()

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [25]:
Z = np.zeros((10,10))
# print("%d bytes"%(2*3))
print(f"{Z.size} * {Z.itemsize} {bytes}")

100 * 8 <class 'bytes'>


In [49]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [20]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [24]:
b=np.ones((3,3))

In [25]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
b = np.ones_like(a)
b

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
b = np.ones_like(a) * 5
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
d=np.full((3,3),5)
d

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [30]:
b=np.full_like(a,5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [31]:
np.full_like(a, dtype=a.dtype, fill_value=2.5)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.full_like(a, dtype=np.float, fill_value=2.5)

array([[2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5]])

In [33]:
np.empty((2,2))

array([[1.03745653e-028, 1.05957293e+214],
       [6.01346953e-154, 1.35712977e+166]])

In [35]:
np.empty((3,4))

array([[1.05513009e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.42051906e+161, 6.45962683e+170,
        8.00992884e+169],
       [4.99509735e+174, 9.76658081e+165, 5.40661798e-066,
        9.94954887e-043]])

In [36]:
np.full_like(a, 1) * np.nan

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [8]:
np.full_like(a,1)*np.nan

array([nan, nan, nan, nan])

In [37]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
Z = np.diag(1+np.arange(4))
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [40]:
a=np.array([1,2,3,4],dtype='int')
a.dtype

dtype('int32')

In [41]:
a=np.array([1,2,3,4],dtype=int)
a.dtype

dtype('int32')

In [42]:
a=np.array([1,2,3,4],dtype=np.int)
a.dtype

dtype('int32')

In [43]:
a=np.array([1,2,3,4],dtype=np.int64)
a.dtype

dtype('int64')

In [44]:
d=np.array([1,2,3,45,65],dtype=a.dtype)
d.dtype

dtype('int64')

In [45]:
a=np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [47]:
a%3==0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [48]:
a[a%3==0]

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [49]:
a[(a%3==0) & (a%5==0)]

array([15])

In [51]:
a[~a%3==0]

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26])

In [52]:
a[~(a%3==0)]

# what is the difference b/t this one and above one

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [54]:
a[a%3!=0]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23, 25,
       26])

In [55]:
z=np.arange(1,7).reshape(2,3,1)
z

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [9]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
print(a[1,2,0])

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]
25


In [11]:
a[[1,2,0]]

array([[[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
a = np.arange(10,3*3*3+10).reshape(3,3,3)
# print(a)

# print()
# print(a[[1,2,0]])
# print(a[[1,2,0]])
# a[[1,2,0],[0,1,2],:]
a[[1,2,0]][:,[1,2,0]]
# a[[1,2,0]][:,[-1,0]]
# a[[1,2,0],:,::-1]
# a[::-1]
# a[:,::-1,:]
# a[[1,2,0]]

array([[[22, 23, 24],
        [25, 26, 27],
        [19, 20, 21]],

       [[31, 32, 33],
        [34, 35, 36],
        [28, 29, 30]],

       [[13, 14, 15],
        [16, 17, 18],
        [10, 11, 12]]])

In [9]:
import numpy as np
names = np.array(["Qasim","Hamza","Ali","Junaid","Qasim","Ali"])
data = np.random.randn(6,4)
print(names,data ,sep="\n")

['Qasim' 'Hamza' 'Ali' 'Junaid' 'Qasim' 'Ali']
[[ 0.92454724  0.06607025  0.38440751  0.31251237]
 [ 1.44822527  0.81812218  1.98370238  0.81091417]
 [-0.52694057  0.10228321 -0.88696151  1.13577413]
 [ 0.71438456  0.12582219 -0.21439556  0.76719734]
 [-0.83845338  0.2001615   1.0473206  -1.04884295]
 [ 1.10990685 -0.50570388 -0.63675666 -0.50544257]]


In [10]:
names=='Qasim'

array([ True, False, False, False,  True, False])

In [14]:
data[names=='Qasim']

array([[ 0.92454724,  0.06607025,  0.38440751,  0.31251237],
       [-0.83845338,  0.2001615 ,  1.0473206 , -1.04884295]])

In [20]:
data[names=='Qasim'][:,[-1,0,2]]

array([[ 0.31251237,  0.92454724,  0.38440751],
       [-1.04884295, -0.83845338,  1.0473206 ]])

In [21]:
data[names=='Qasim'][:,::-1]

array([[ 0.31251237,  0.38440751,  0.06607025,  0.92454724],
       [-1.04884295,  1.0473206 ,  0.2001615 , -0.83845338]])

In [22]:
names=np.array(['sohail','Ali','junaid','sohail','Hamza','Ali'])
data=np.random.randn(6,4)
print(names,data,sep="\n")

['sohail' 'Ali' 'junaid' 'sohail' 'Hamza' 'Ali']
[[-0.31692367  1.43408611  0.41954557  0.25213773]
 [-2.46190686 -0.14683461 -0.63148562 -0.22473312]
 [-0.44387937  1.18911376  0.50122499  0.16873386]
 [-1.85416834 -0.47709372 -1.07542478  0.83363936]
 [ 0.1268051   0.38671463  1.47811246 -0.40752767]
 [ 1.49928507  1.61073769  0.36217714 -1.22592935]]


In [24]:
data[names=='Hamza']

array([[ 0.1268051 ,  0.38671463,  1.47811246, -0.40752767]])

In [26]:
data[(names=="sohail")|(names=='Ali')]

array([[-0.31692367,  1.43408611,  0.41954557,  0.25213773],
       [-2.46190686, -0.14683461, -0.63148562, -0.22473312],
       [-1.85416834, -0.47709372, -1.07542478,  0.83363936],
       [ 1.49928507,  1.61073769,  0.36217714, -1.22592935]])

In [28]:
data[~(names=="sohail")| ~(names=='Ali')]

array([[-0.31692367,  1.43408611,  0.41954557,  0.25213773],
       [-2.46190686, -0.14683461, -0.63148562, -0.22473312],
       [-0.44387937,  1.18911376,  0.50122499,  0.16873386],
       [-1.85416834, -0.47709372, -1.07542478,  0.83363936],
       [ 0.1268051 ,  0.38671463,  1.47811246, -0.40752767],
       [ 1.49928507,  1.61073769,  0.36217714, -1.22592935]])

In [37]:
print(data[(names !="sohail")])
print()
print(data[:,::-1])

[[-2.46190686 -0.14683461 -0.63148562 -0.22473312]
 [-0.44387937  1.18911376  0.50122499  0.16873386]
 [ 0.1268051   0.38671463  1.47811246 -0.40752767]
 [ 1.49928507  1.61073769  0.36217714 -1.22592935]]

[[ 0.25213773  0.41954557  1.43408611 -0.31692367]
 [-0.22473312 -0.63148562 -0.14683461 -2.46190686]
 [ 0.16873386  0.50122499  1.18911376 -0.44387937]
 [ 0.83363936 -1.07542478 -0.47709372 -1.85416834]
 [-0.40752767  1.47811246  0.38671463  0.1268051 ]
 [-1.22592935  0.36217714  1.61073769  1.49928507]]


In [38]:
a  = np.arange(3*3*3).reshape(3,3,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [39]:
a[[-1,0,2],:,:]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [41]:
a[[-2,-1,0]]

array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [42]:
a[:,[0,1],:]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 9, 10, 11],
        [12, 13, 14]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [44]:
a[:,1:,:]

array([[[ 3,  4,  5],
        [ 6,  7,  8]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[21, 22, 23],
        [24, 25, 26]]])

In [99]:
l=[1,22,43,5,6,7,5,43,65]
l[:3]

[1, 22, 43]

In [100]:
l[:4]=77

TypeError: can only assign an iterable

In [47]:
a[1]=55

In [48]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[55, 55, 55],
        [55, 55, 55],
        [55, 55, 55]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [49]:
a = np.arange(3*3).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
a[1:,1:]

array([[4, 5],
       [7, 8]])

In [51]:
a[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [52]:
a[-2:,-2:]

array([[4, 5],
       [7, 8]])

In [53]:
a[-1:,-1:]

array([[8]])

In [55]:
a=np.arange(1,8*4+1).reshape(8,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [57]:
for i in range(len(a)):
    a[i]=i+1
print(a)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]


In [59]:
for i in range(a.shape[0]):
    a[i]=i+1
print(a)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]


In [60]:
for i ,_ in enumerate(a):
    a[i]=i+1
print(a)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]
 [8 8 8 8]]


In [62]:
list(enumerate([8,7,6,5,9]))

[(0, 8), (1, 7), (2, 6), (3, 5), (4, 9)]

In [64]:
a

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7],
       [8, 8, 8, 8]])

In [65]:
a[[3,4,5]]

array([[4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6]])

In [69]:
a = np.arange(8*4).reshape((8,4))
print(a)
a[[5,4,3]][:,[3,1]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[23, 21],
       [19, 17],
       [15, 13]])

In [68]:
a=np.arange(8*4).reshape(8,4)
print(a)
a[[5,4,3]][:,[1,2,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[21, 22, 23],
       [17, 18, 19],
       [13, 14, 15]])

In [70]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [71]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [2]:
import numpy as np
a=np.arange(4*3).reshape(4,3)
print(a)
print(a.T)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [8]:
print(a.transpose())

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [10]:
a=np.array([[1,2],[3,4]])
b=a+2
print(a,b , sep='\n\n',end="\n\n")
print(a*b)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 3  8]
 [15 24]]


In [11]:
a@b

array([[13, 16],
       [29, 36]])

In [12]:
a.dot(b)

array([[13, 16],
       [29, 36]])

In [20]:
print(a,b,sep="\n\n",end="\n\n")
print(a.dot(a),end='\n\n')
print(a@a.T,end='\n\n')
print(a@a)

[[1 2]
 [3 4]]

[[3 4]
 [5 6]]

[[ 7 10]
 [15 22]]

[[ 5 11]
 [11 25]]

[[ 7 10]
 [15 22]]


In [26]:
a=np.arange(1,28).reshape(3,3,3)
print(a,end='\n\n')
print(a.T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


In [29]:
print(a,end='\n\n')
print(a.transpose((0,2,1)))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[ 1  4  7]
  [ 2  5  8]
  [ 3  6  9]]

 [[10 13 16]
  [11 14 17]
  [12 15 18]]

 [[19 22 25]
  [20 23 26]
  [21 24 27]]]


In [31]:
print(a,end='\n\n')
print(a.transpose((2,1,0)))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


In [37]:
a=np.arange(4*3).reshape(4,3)
print(a,end='\n\n')
print(a.swapaxes(1,0),end='\n\n')
#print(a.reshape((a.shape[1], a.shape[0])))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]



In [38]:
print(a)
print()
print(a.reshape(a.shape[1],a.shape[0]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
a.shape

(4, 3)

In [41]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
a.swapaxes(1,0)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [51]:
np.swapaxes(a,1,0)

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [47]:
l=np.array([1,2,3,-4,5,-3,-6,-45])
np.abs(l)

array([ 1,  2,  3,  4,  5,  3,  6, 45])

In [53]:
l = np.array([-1,3.2,-5.4,-8.2,0.7])
np.fabs(l)

array([1. , 3.2, 5.4, 8.2, 0.7])

In [54]:
np.sqrt([36,25,9])

array([6., 5., 3.])

In [56]:
print(np.square([4,5,6,7,8]))

[16 25 36 49 64]


In [57]:
np.exp([3,4,5])

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [58]:
np.ceil([2.1,3.5,5,7,4.4])

array([3., 4., 5., 7., 5.])

In [59]:
np.floor([3.3,4.1,3.2,5.6])

array([3., 4., 3., 5.])

In [60]:
a = np.array([2.2, 3.1, 2.6])
print(a)
print()
f, w = np.modf(a)
print(w,f, sep="\n\n")

[2.2 3.1 2.6]

[2. 3. 2.]

[0.2 0.1 0.6]


In [64]:
for i in [2.2, 3.1, 2.6]:
    i=str(i).split('.')
    print(i[0],i[1])

2 2
3 1
2 6


In [22]:
for i in [2.2,3.1,2.6,4.3]:
    i=str(i).split('.')
    print(i[0],i[1])

2 2
3 1
2 6
4 3


In [65]:
a = np.arange(6*2).reshape((6,2))
np.meshgrid(a,a)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
        [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
        [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
        [ 5,

In [25]:
x=np.linspace(-4,4,7)
x

array([-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
        2.66666667,  4.        ])

In [27]:
y=np.linspace(-5,5,9)
y

array([-5.  , -3.75, -2.5 , -1.25,  0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [28]:
m=np.meshgrid(x,y)
m

[array([[-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ],
        [-4.        , -2.66666667, -1.33333333,  0.        ,  1.33333333,
          2.66666667,  4.        ]]),
 array([

In [101]:
np.meshgrid??

In [72]:
a = np.arange(3*3*3).reshape((3,3,3))
a %3 == 0

array([[[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False],
        [ True, False, False]]])

In [29]:
a[a%3==0]

array([12, 15, 18, 21, 24, 27, 30, 33, 36])

In [74]:
print(a)
a[1][1][1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


13

In [32]:
# a[1][1][1]
# print(a[1:],[1],[1])

[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]] [1] [1]


In [68]:
c = np.arange(3*3*3).reshape((3,3,3))
np.where(c%3==0,'OK','NotOk')

array([[['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk']],

       [['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk']],

       [['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk'],
        ['OK', 'NotOk', 'NotOk']]], dtype='<U5')

In [69]:
a = np.array([1,3,45])
b = np.array([2,4,3])

print(np.where(a>b, a, b))

[ 2  4 45]


In [70]:
def abc(x):
    try:
        x = str(x)
        return np.int64("".join([i for i in x if str.isnumeric(i)]))
    except:
        return 0
    
abc("kjadjslkljskldksljkl3askjd-asdfl;ak3")
# dry run??

33

In [1]:
import numpy as np
a=np.arange(1,7)
b=a+5
print(a,b,sep="\n")

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [4]:
np.stack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [5]:
np.stack((a,b),axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [6]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [7]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
x=np.arange(1,7)
y=x+6
print(x,y,sep='\n')

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [14]:
np.hstack((x,y))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [15]:
np.vstack((x,y))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
a = np.arange(1,2*2*2+1).reshape((2,2,2))
b = a + 5
print(a,b,sep='\n\nSecond\n\n',end="\n\n")

np.dstack((a,b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Second

[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]



array([[[ 1,  2,  6,  7],
        [ 3,  4,  8,  9]],

       [[ 5,  6, 10, 11],
        [ 7,  8, 12, 13]]])

In [33]:
np.dstack??

In [36]:
np.split??

In [34]:
e=np.arange(1,37).reshape(6,6)
print(e,sep='\n\n')
np.split(e,3,axis=0)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]), array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [39]:
np.split(e,6,axis=0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36]])]

In [37]:
np.split(e,2,axis=0)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [42]:
a=np.arange(1,37).reshape(6,6)
print(a,sep='\n\n')
print(np.split(a,2,axis=1))
print(np.split(a,2,axis=0))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21],
       [25, 26, 27],
       [31, 32, 33]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18],
       [22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])]
[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])]


In [43]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]), array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [44]:
a=np.random.randint(1,10,size=(3,5))
a

array([[1, 6, 7, 6, 7],
       [1, 4, 3, 5, 1],
       [8, 9, 9, 8, 9]])

In [45]:
a+5

array([[ 6, 11, 12, 11, 12],
       [ 6,  9,  8, 10,  6],
       [13, 14, 14, 13, 14]])

In [46]:
a

array([[1, 6, 7, 6, 7],
       [1, 4, 3, 5, 1],
       [8, 9, 9, 8, 9]])

In [47]:
a=np.random.randn(3,4)
a

array([[ 1.32272253, -1.67813335, -0.53587205, -0.38404089],
       [ 1.23501406,  2.10911302, -0.21417123, -0.9458295 ],
       [ 1.03295616, -1.24164691, -0.49138131,  0.33282589]])

In [51]:
s=np.random.randint(1,10,size=20)
w=np.random.randint(5,14,size=7)
[True if i in s else False for i in w ]

[True, True, False, True, True, True, False]

In [52]:
np.in1d(w,s)

array([ True,  True, False,  True,  True,  True, False])

In [54]:
print(w,s,sep='\n')
np.intersect1d(w,s)

[ 8  9 10  7  5  7 10]
[3 6 6 8 4 5 4 6 2 7 5 5 5 1 5 2 9 8 6 8]


array([5, 7, 8, 9])

In [40]:
a=np.random.randint(1,10,size=20)
b=np.random.randint(1,10,size=5)
print(a,b,sep='\n')
np.setdiff1d(b,a)

[9 5 2 4 4 5 8 5 9 6 4 9 8 9 3 6 1 3 3 8]
[9 4 7 8 1]


array([7])

In [57]:
np.setxor1d(b,a)

array([1, 2, 3, 4, 5, 6])

ReWork

In [58]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.07528551  1.13075587  1.05878165  0.93774055  0.66345661]
 [-1.64041361  0.95360919  0.55237911  0.89291566  0.47014869]
 [-0.94840445 -1.77943467  0.73747815 -1.63310368 -1.02287376]
 [-0.17000243  0.8547075  -0.25436279  0.86078449 -1.36408621]
 [ 0.88370187 -1.06388202 -1.39926817  0.54327231  0.66081462]]


In [63]:
Z = np.random.random((5,5))
np.std(Z)

0.29762070099333626

In [60]:
z

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [66]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [67]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [69]:
Z = np.arange(11)
Z[(3 <= Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [78]:
print(sum(range(5),-1))

9


In [76]:
x=np.arange(5)
x

array([0, 1, 2, 3, 4])

In [79]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\Warraich\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\Warraich\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [80]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [81]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 2 5]


In [83]:
Z1

array([0, 9, 2, 5, 9, 3, 1, 2, 1, 9])

In [84]:
np.intersect1d(Z1,Z2)

array([0, 1, 2, 5])

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Warraich\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [86]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

In [87]:
np.datetime64('today')

numpy.datetime64('2020-07-17')

In [91]:
print(np.timedelta64(1))

1 generic time units


In [92]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [93]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [98]:
np.add(A,B)

array([1.5, 1.5, 1.5])

In [102]:
c=np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
c[5:8]=11

In [117]:
c

array([ 0,  1,  2,  3,  4, 11, 11, 11,  8,  9])

In [118]:
c[6:2]

array([], dtype=int32)

In [119]:
c[2:6]

array([ 2,  3,  4, 11])

In [121]:
a=np.array([[1,2,3],[4,5,6]],float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [122]:
a[-1:,-2:]

array([[5., 6.]])

In [124]:
a=np.arange(10,dtype=float)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [126]:
a=np.array(range(10,20),float)
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [127]:
a.reshape(5,2)

array([[10., 11.],
       [12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.]])

In [128]:
a

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [129]:
len(a)

10

In [130]:
a=a.reshape(5,2)

In [131]:
len(a)

5

In [132]:
type(a)

numpy.ndarray

In [133]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [134]:
a.tolist()

[1, 2, 3]

In [135]:
type(a)

numpy.ndarray

In [136]:
list(a)

[1, 2, 3]

In [137]:
type(a)

numpy.ndarray

In [139]:
a=np.array([1,2,3])
print(type(a))
s=a.tolist()
type(s)

<class 'numpy.ndarray'>


list

In [140]:
x=a.tostring()
x

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00'

In [144]:
np.fromstring(x)

C:\Users\Warraich\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


ValueError: string size must be a multiple of element size

In [149]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [150]:
a.fill(0)

In [151]:
a

array([0, 0, 0])

In [154]:
z=np.array(range(6)).reshape((3,2))
z

array([[0, 1],
       [2, 3],
       [4, 5]])

In [156]:
z=np.arange(6).reshape(3,2)
z

array([[0, 1],
       [2, 3],
       [4, 5]])

In [157]:
z.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

In [160]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [163]:
zx=a.flatten()

In [164]:
a.ndim

2

In [165]:
zx.ndim

1

In [167]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
np.concatenate((a, b, c))

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [168]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
np.concatenate((a,b))

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [170]:
np.concatenate((a,b),axis=0)

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [171]:
np.concatenate((a,b),axis=1)

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [172]:
a

array([[1., 2.],
       [3., 4.]])

In [173]:
b

array([[5., 6.],
       [7., 8.]])

In [176]:
a=np.array([7,8,9])
a[:,np.newaxis].shape

(3, 1)

In [175]:
a.shape

(3,)

In [179]:
b[:,np.newaxis]

array([[[5., 6.]],

       [[7., 8.]]])

In [184]:
b.shape

(2, 2)

In [183]:
b[:,np.newaxis]

array([[[5., 6.]],

       [[7., 8.]]])

In [185]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [186]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [188]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [189]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [190]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [191]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [193]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [194]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [199]:
print(a-b)
print(b-a)
print(a*b)
print(a**b)
print(b**a)
print(a/b)

[-3 -3 -3]
[3 3 3]
[ 4 10 18]
[  1  32 729]
[  4  25 216]
[0.25 0.4  0.5 ]


In [200]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
a * b
# array([[2., 0.], [3., 12.]])


array([[ 2.,  0.],
       [ 3., 12.]])

In [201]:
print(a)
print(b)

[[1. 2.]
 [3. 4.]]
[[2. 0.]
 [1. 3.]]


In [203]:
a = np.array([1.1, 1.5, 1.9], float)
print(np.floor(a))
# array([ 1., 1., 1.])
print(np.ceil(a))
# array([ 2., 2., 2.])
print(np.rint(a))
# array([ 1., 2., 2.])


[1. 1. 1.]
[2. 2. 2.]
[1. 2. 2.]


In [204]:
np.pi

3.141592653589793

In [205]:
np.e

2.718281828459045

In [206]:
a=np.array([1,4,7])
for i in a:
    print(i)

1
4
7


In [207]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [208]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [209]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x,y in a:
    print(x*y)

2.0
12.0
30.0


In [210]:
a=np.array([2,4,5])
a.sum()

11

In [211]:
np.sum(a)

11

In [212]:
a.prod()

40

In [213]:
np.prod(a)

40

In [220]:
a=np.array([2,1,9])
print(np.mean(a))
print(np.var(a))
print(a.std())

4.0
12.666666666666666
3.559026084010437


In [215]:
a.mean()

4.0

In [222]:
c=np.array([2,3,4,5,6,7,9])
c.argmin()
# return the index of min value

0

In [223]:
c.argmax()
# return the index of maximum value

6

In [224]:
len(c)

7

In [230]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
print(a.mean(axis=0))
# dry run?
a

[2. 2.]


array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [227]:
a.mean(axis=1)
# dry run?

array([1., 1., 4.])

In [228]:
a.mean(axis=0)

array([2., 2.])

In [236]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [237]:
a

array([ 6.,  2.,  5., -1.,  0.])

In [238]:
a.sort()

In [239]:
a

array([-1.,  0.,  2.,  5.,  6.])

In [241]:
a = np.array([6, 2, 5, -1, 0], float)
np.clip(a,0,5)

array([5., 2., 5., 0., 0.])

In [242]:
a

array([ 6.,  2.,  5., -1.,  0.])

In [246]:
d=np.array([3,4,5,3,5,2,1,1,2,1])
np.unique(d)

array([1, 2, 3, 4, 5])

In [248]:
a=np.array([[1,2,3],[3,4,5]])
np.diagonal(a)

array([1, 4])

In [249]:
a=np.array([1,3,0])
b=np.array([0,3,2])
a>b

array([ True, False, False])

In [250]:
a==b

array([False,  True, False])

In [251]:
b=np.array([True,True,False,True,False,False])
np.any(b)

True

In [252]:
np.all(b)

False

In [3]:
import numpy as np
a = np.array([1, 3, 0,2,4,2], float)
np.logical_and(a>1,a<4)

array([False,  True, False,  True, False,  True])

In [4]:
np.logical_or(a>1,a<4)

array([ True,  True,  True,  True,  True,  True])

In [5]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [6]:
a = np.array([1, 3, 0], float)
np.where(a != 0, 1 / a, a)

C:\Users\Warraich\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([1.        , 0.33333333, 0.        ])

In [7]:
np.where(a>0,3,2)

array([3, 3, 2])

In [8]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [9]:
a[a >= 6]

array([6., 9.])

In [10]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

In [2]:
f=np.array([[1,0],[0,3]])
np.nonzero(f)
            

(array([0, 1], dtype=int64), array([0, 1], dtype=int64))

In [3]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan()

array([False,  True, False])

In [4]:
np.isfinite(a)

array([ True, False, False])

In [5]:
a = np.array([[6, 4], [5, 9]], float)
a>=6

array([[ True, False],
       [False,  True]])

In [6]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]
# dry run???
# why this output?

array([2., 2., 4., 8., 6., 4.])

In [7]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]
# Dry run??

array([2., 2., 4., 8., 6., 4.])

In [8]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [9]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)
# ?????
# dry run?

array([2., 2., 4., 8., 6., 4.])

In [10]:
# the opposite of take function is put function
# what is take and put function

In [11]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a,b)

5.0

In [2]:
import numpy as np
a = np.array([1, 4, 3, 8, 9, 2, 3], float)
np.mean(a)

4.285714285714286

In [4]:
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float)
c = np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [5]:
np.var(a)

5.25